export const PROJECT_LIST_REQUEST: string = "PROJECT_LIST_REQUEST";
export const PROJECT_LIST_SUCCESS: string = "PROJECT_LIST_SUCCESS";
export const PROJECT_LIST_FAIL: string = "PROJECT_LIST_FAIL";

export const PROJECT_DETAILS_REQUEST: string = "PROJECT_DETAILS_REQUEST";
export const PROJECT_DETAILS_SUCCESS: string = "PROJECT_DETAILS_SUCCESS";
export const PROJECT_DETAILS_FAIL: string = "PROJECT_DETAILS_FAIL";
